### ISSUE TITLE
[after installing on odoo V11-ce] Web Lead Funnel Chart

### ISSUE THREAD

**Issue by ajit-radometech** [JayVora-SerpentCS/SerpentCS_Contributions-v8#389] opened 2019-10-21 11:43 UTC
when click on Funnel Chart in CRM module
Action Error
Could not find client action 'web_lead_funnel_chart.funnel'.
is displayed in pop-up

**Comment by JayVora-SerpentCS** [comment] 2019-10-26 14:20
@nikitavaghela

**Comment by nikitavaghela** [comment] 2019-11-27 11:36
Hello @ajit-radometech,
I tested this module in a new database. I didn't get any error. so can you please list out steps or show me an issue in the video. so I can check the exact issue.

**Comment by Savitri-SerpentCS** [comment] 2020-02-18 13:14
I have checked this one and I'm not able to Reproduce this issue too.

@JayVora-SerpentCS  We can close this one.

**Closed as completed** 2020-02-18 13:19 UTC
