### ISSUE TITLE
After uninstall of this Module in v10 Enterprise I get attached error on Click on any User

### ISSUE THREAD

**Issue by abhinavvaidya90** [JayVora-SerpentCS/SerpentCS_Contributions-v8#331] opened 2019-04-02 10:35 UTC
After uninstall of this Module in v10, I go to
Settings > Users > Click on any User 

![image](https://user-images.githubusercontent.com/24862587/55396208-5a836b80-5569-11e9-87a8-3c7ff81df2d1.png)

**Comment by JayVora-SerpentCS** [comment] 2019-04-19 11:08
@swapnesh-serpentcs Plz chk

**Comment by Swapnesh-SerpentCS** [comment] 2019-04-19 11:16
Hello @abhinavvaidya90,
Thanks for Reporting this to us.

> After uninstall of this Module in v10

Can you please add some more description?

- Which module Did you Uninstalled?
 - ~~Is it for Odoo community version or Enterprise~~? Sorry, You have already  mentioned this on Issue label. (This is for v10  `Enterprise`)

 
Thanks.

**Comment by JayVora-SerpentCS** [comment] 2019-05-09 05:05
@abhinavvaidya90 closing the matter till you respond.
Thanks. Will reopen if the issue is encountered again.

**Closed as completed by JayVora-SerpentCS** 2019-05-09 05:05 UTC
